#!/usr/bin/env bash

# Check if the system has engineer installed, if not, use a local copy.
if ! type "engineer" > /dev/null; then
    set -e
    # Setup Prisma engine build & test tool (engineer).
    curl --fail -sSL https://prisma-engineer.s3-eu-west-1.amazonaws.com/latest/engineer.gz --output engineer.gz
    gzip -d engineer.gz
    chmod +x engineer

    # Execute passed command and clean up
    ./engineer $@
    rm -rf ./engineer
else
    set -e
    # Already installed on the system
    engineer $@
fi