#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    OS=linux-amzn
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS=darwin
else
    echo "Unhandled OS: '$OSTYPE'"
    exit 1
fi

# Check if the system has engineer installed, if not, use a local copy.
if ! type "engineer" > /dev/null; then
    set -e
    # Setup Prisma engine build & test tool (engineer).
    curl --fail -sSL "https://prisma-engineer.s3-eu-west-1.amazonaws.com/pgbouncer/84cc189f11129da9049fd3ff5a28af04e6b86d1f/$OS/engineer.gz" --output engineer.gz
    gzip -d engineer.gz
    chmod +x engineer

    # Execute passed command and clean up
    ./engineer $@
    rm -rf ./engineer
else
    set -e
    # Already installed on the system
    engineer $@
fi
