use serde::de::DeserializeOwned;
use std::fmt;

/// represents an instance of a native type declared in the Prisma schema
#[derive(Debug)]
pub struct NativeTypeInstance {
    /// the name of the native type used in the Prisma schema
    pub name: String,
    /// the arguments that were provided
    pub args: Vec<String>,
    /// the serialized representation of this native type. The serialized format is generated by the `native-types` library
    pub serialized_native_type: serde_json::Value,
}

impl fmt::Display for NativeTypeInstance {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.name)?;

        if !self.args.is_empty() {
            f.write_str("(")?;
            f.write_str(&self.args.join(","))?;
            f.write_str(")")?;
        }

        Ok(())
    }
}

impl NativeTypeInstance {
    pub fn new(name: &str, args: Vec<String>, serialized_native_type: serde_json::Value) -> Self {
        NativeTypeInstance {
            name: name.to_string(),
            args,
            serialized_native_type,
        }
    }

    pub fn deserialize_native_type<T>(&self) -> T
    where
        T: DeserializeOwned,
    {
        let error_msg = format!(
            "Deserializing the native type from json failed: {:?}",
            self.serialized_native_type.as_str()
        );
        serde_json::from_value(self.serialized_native_type.clone()).expect(&error_msg)
    }
}
